[package]
name = "libp2p-secio"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"

[dependencies]
asn1_der = "0.5"
bytes = "0.4"
futures = "0.1"
libp2p-core = { path = "../core" }
log = "0.4.1"
protobuf = "2.0.2"
rand = "0.3.17"
ring = { version = "0.12.1", features = ["rsa_signing"] }
aes-ctr = "0.1.0"
aesni = { version = "0.4.1", features = ["nocheck"], optional = true }
ctr = { version = "0.1", optional = true }
lazy_static = { version = "0.2.11", optional = true }
rw-stream-sink = { path = "../rw-stream-sink" }
eth-secp256k1 = { git = "https://github.com/paritytech/rust-secp256k1", optional = true }
tokio-io = "0.1.0"
untrusted = "0.5.1"

[features]
default = ["secp256k1"]
secp256k1 = ["eth-secp256k1"]
aes-all = ["ctr","aesni","lazy_static"]

[dev-dependencies]
libp2p-tcp-transport = { path = "../tcp-transport" }
tokio-current-thread = "0.1"
tokio-tcp = "0.1"
