[package]
name = "libp2p-tls-quic"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "MIT"
description = "A libp2p transport using TLS+QUIC"
keywords = ["peer-to-peer", "libp2p", "quic", "networking"]
categories = ["network-programming", "asynchronous"]

[dependencies]
libp2p-core = { path = "../../core", version = "0.29.0" }
rcgen = "0.8.11"
x509-parser = "0.9.2"
der-parser = { version = "5.1.0", features = ["serialize"] }
oid-registry = "0.1.5"
yasna = "0.4.0"
rustls = "0.19.1"
ring = "0.16.20"
