[package]
name = "datastore"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"

[dependencies]
base64 = "0.7"
chashmap = { git = "https://github.com/redox-os/tfs" }
futures = "0.1"
serde = "1.0"
serde_json = "1.0"
tempfile = "2.2"
