sudo: required
language: rust
branches:
  only:
  - master

before_install:
  # Add an IPv6 config - see the corresponding Travis issue
  # https://github.com/travis-ci/travis-ci/issues/8361
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then 
      sudo sh -c 'echo 0 > /proc/sys/net/ipv6/conf/all/disable_ipv6';
    fi
  - rustup component add rustfmt-preview

cache: cargo

matrix:
  fast_finish: false
  include:
    - rust: stable

script:
  #- cargo fmt -- --write-mode=diff
  - cargo check --all
  - cargo test --all
