[package]
name = "libp2p-tls"
version = "0.5.0"
edition = "2021"
rust-version = { workspace = true }
description = "TLS configuration based on libp2p TLS specs."
repository = "https://github.com/libp2p/rust-libp2p"
license = "MIT"
exclude = ["src/test_assets"]

[dependencies]
futures = { workspace = true }
futures-rustls = { workspace = true }
libp2p-core = { workspace = true }
libp2p-identity = { workspace = true }
rcgen = { workspace = true }
ring = { workspace = true }
thiserror = { workspace = true }
webpki = { version = "0.101.4", package = "rustls-webpki", features = ["std"] }
x509-parser = "0.16.0"
yasna = "0.5.2"

# Exposed dependencies. Breaking changes to these are breaking changes to us.
[dependencies.rustls]
version = "0.23.9"
default-features = false
features = ["ring", "std"] # Must enable this to allow for custom verification code.


[dev-dependencies]
hex = "0.4.3"
hex-literal = "0.4.1"
libp2p-core = { workspace = true }
libp2p-identity = { workspace = true, features = ["ed25519", "rsa", "secp256k1", "ecdsa", "rand"] }
libp2p-swarm = { workspace = true, features = ["tokio"] }
libp2p-yamux = { workspace = true }
tokio = { workspace = true, features = ["full"] }

# Passing arguments to the docsrs builder in order to properly document cfg's.
# More information: https://docs.rs/about/builds#cross-compiling
[package.metadata.docs.rs]
all-features = true

[lints]
workspace = true
