[package]
name = "libp2p-tls"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = { version = "0.3.24", default-features = false }
futures-rustls = "0.22.2"
libp2p-core = { version = "0.36.0", path = "../../core" }
rcgen = "0.9.2"
ring = "0.16.20"
rustls = { version = "0.20.2", default-features = false, features = ["dangerous_configuration"] } # Exposed dependency! Bump major version on any change.
thiserror = "1.0.36"
webpki = "0.22.0"
x509-parser = "0.14.0"
yasna = "0.5.0"

[dev-dependencies]
hex = "0.4.3"
hex-literal = "0.3.4"
libp2p = { path = "../..", features = ["yamux"], default-features = false }
tokio = { version = "1.21.1", features = ["full"] }
