[package]
name = "libp2p-muxer-test-harness"
version = "0.1.0"
edition = "2021"
publish = false
license = "MIT"

[package.metadata.release]
release = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libp2p-core = { workspace = true }
futures = { workspace = true }
futures-timer = "3.0.3"
futures_ringbuf = "0.4.0"
tracing = { workspace = true }

[lints]
workspace = true
