[package]
name = "libp2p-muxer-test-harness"
version = "0.1.0"
edition = "2021"
publish = false
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libp2p-core = { workspace = true }
futures = "0.3.28"
log = "0.4"
futures-timer = "3.0.2"
futures_ringbuf = "0.4.0"

[lints]
workspace = true