[package]
name = "libp2p-stream"
version = "0.2.0-alpha.1"
edition = "2021"
rust-version.workspace = true
description = "Generic stream protocols for libp2p"
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]

[dependencies]
futures = { workspace = true }
libp2p-core = { workspace = true }
libp2p-identity = { workspace = true, features = ["peerid"] }
libp2p-swarm = { workspace = true }
tracing = { workspace = true }
rand = "0.8"

[dev-dependencies]
libp2p-swarm-test = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[lints]
workspace = true
