[package]
name = "parity-multiaddr"
edition = "2018"
authors = ["dignifiedquire <dignifiedquire@gmail.com>", "Parity Technologies <admin@parity.io>"]
description = "Implementation of the multiaddr format"
homepage = "https://github.com/libp2p/rust-libp2p"
keywords = ["multiaddr", "ipfs"]
license = "MIT"
version = "0.5.0"

[dependencies]
arrayref = "0.3"
bs58 = "0.3.0"
byteorder = "1.3.1"
bytes = "0.4.12"
data-encoding = "2.1"
multihash = { package = "parity-multihash", version = "0.1.0", path = "../multihash" }
percent-encoding = "2.1.0"
serde = "1.0.70"
unsigned-varint = "0.2"
url = { version = "2.1.0", default-features = false }

[dev-dependencies]
bincode = "1"
bs58 = "0.3.0"
data-encoding = "2"
quickcheck = "0.9.0"
rand = "0.7.2"
serde_json = "1.0"
