[package]
authors = ["dignifiedquire <dignifiedquire@gmail.com>"]
description = "Implementation of the multiaddr format"
homepage = "https://github.com/multiformats/rust-multiaddr"
keywords = ["multiaddr", "ipfs"]
license = "MIT"
name = "multiaddr"
readme = "README.md"
version = "0.3.0"

[dependencies]
arrayref = "0.3"
bs58 = "0.2.0"
byteorder = "0.4"
data-encoding = "2.1"
multihash = { path = "../multihash" }
serde = "1.0.70"
unsigned-varint = "0.2"

[dev-dependencies]
bincode = "1"
bs58 = "0.2.0"
data-encoding = "2"
multihash = { path = "../multihash" }
quickcheck = "0.7"
rand = "0.6"
serde_json = "1.0"