[package]
name = "varint"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
num-bigint = { version = "0.1.41", default-features = false }
num-traits = "0.2"
bytes = "0.4.5"
tokio-io = "0.1"
futures = "0.1"
error-chain = "0.11.0"
