[package]
name = "libp2p-core-derive"
description = "Procedural macros of libp2p-core"
version = "0.2.1"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15.22", default-features = false, features = ["clone-impls", "derive", "parsing", "printing", "proc-macro"] }
quote = "0.6"

[dev-dependencies]
libp2p = { version = "0.2.2", path = "../.." }
void = "1.0"
