[package]
name = "libp2p-tcp-transport"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
libp2p-core = { path = "../core" }
log = "0.4.1"
futures = "0.1"
multiaddr = "0.3.0"
tokio-core = "0.1"
tokio-io = "0.1"
