[package]
name = "libp2p-tcp-transport"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
libp2p-core = { path = "../core" }
log = "0.4.1"
futures = "0.1"
multiaddr = { path = "../multiaddr" }
tokio-tcp = "0.1"

[dev-dependencies]
tokio-current-thread = "0.1"
tokio-io = "0.1"
