[package]
name = "circular-buffer"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
smallvec = { git = "https://github.com/Vurich/rust-smallvec.git", branch = "array-zero" }