[package]
name = "libp2p-tor"
edition = "2018"
description = "TCP/IP transport protocol for libp2p over the Tor network"
version = "0.20.0"
authors = ["Tobin C. Harding <tobin@coblox.tech>"]
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking", "tor"]
categories = ["network-programming", "asynchronous"]

[dependencies]
data-encoding = "2.2"
futures = "0.3.1"
futures-timer = "3.0"
get_if_addrs = "0.5.3"
ipnet = "2.0.0"
libp2p-core = { version = "0.20.0", path = "../../core" }
log = "0.4.1"
socket2 = "0.3.12"
tokio = { version = "0.2", default-features = false, features = ["tcp"] }
tokio-socks = "0.2"
