[package]
name = "libp2p-ratelimit"
edition = "2018"
description = "Transfer rate limiting transport adapter for libp2p"
version = "0.10.0"
authors = ["Parity Technologies <admin@parity.io>"]
license = "MIT"
repository = "https://github.com/libp2p/rust-libp2p"
keywords = ["peer-to-peer", "libp2p", "networking"]
categories = ["network-programming", "asynchronous"]

[dependencies]
aio-limited = "0.1"
bytes = "0.4"
futures = "0.1"
libp2p-core = { version = "0.10.0", path = "../../core" }
log = "0.4"
tokio-executor = "0.1"
tokio-io = "0.1"
