[package]
name = "libp2p-ratelimit"
version = "0.1.1"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
aio-limited = { git = "https://github.com/paritytech/aio-limited.git" }
futures = "0.1"
libp2p-core = { path = "../core" }
log = "0.4"
tokio = "0.1"
tokio-io = "0.1"
